name: atl_inventory
description: "ATL Inventory - Atal Tinkering Lab Component Tracker"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.0.0
  image_picker: ^1.0.4
  connectivity_plus: ^5.0.2
  uuid: ^4.4.0
  mobile_scanner: ^5.1.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/banner.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/banner.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.jpg
    - lib/assets/default_part.jpg
    - lib/assets/banner.png
